### PR TITLE
Remove return type for make()

### PR DESCRIPTION
**Pull request by Casmo**
Remove static return type. See https://github.com/lorisleiva/laravel-actions/pull/285#issuecomment-2296463178

### CODE REVIEW

**Comment by Casmo** [comment]
Done!

**Comment by lorisleiva** [comment]
Thanks!

**Comment by austincarpenter** [comment]
This has broken IDE autocompletion for me. Now PhpStorm thinks `handle()` when called via `::make()->handle(...)` points to `vendor/laravel/framework/src/Illuminate/Foundation/Application.php`'s `handle()` method.

I deliberately don't use the `::run()` syntax for this reason.

**Comment by lorisleiva** [comment]
@austincarpenter Hi there, this was a partial revert of https://github.com/lorisleiva/laravel-actions/pull/285 which was only published a `patch` version earlier (in the matter of days). When did you experience that autocompletion working and then not working?

**Comment by austincarpenter** [comment]
@lorisleiva Prior to #285 it was working due to the docblock, also after due to the return type and now post #287 it's not due to neither a docblock nor a return type.

**Comment by lorisleiva** [comment]
Gotcha, so we just need the docblock back right? If so, would you be able to submit a small PR for this and I'll get that merged/patched immediately?

**Comment by austincarpenter** [comment]
Apologies for the delay on this one. Thanks @TaylorWilton @lorisleiva 👏

**Pull request merged**
