### PR TITLE
Support controllers with explicit methods

### PR DESCRIPTION
**Pull request by lorisleiva**
See #110

### CODE REVIEW

**Comment by Wulfheart** [comment]
Is this feature documented yet?

**Comment by lorisleiva** [comment]
No it's a good point but I'm not sure this is the sort of behaviour we should encourage for Laravel Actions since you end up with multiple actions within the same class. But it is definitely something that should work if they try it so that's why I made the fix. Do you think we should document it still?

**Comment by Wulfheart** [comment]
But especially for showing a form and handling that it would be really awesome.

**Comment by lorisleiva** [comment]
Alrighty, I'll add something on the guide page. 🙂

**Comment by Wulfheart** [comment]
But we could also discuss if there is or should be a better way to handle this use case?

**Comment by lorisleiva** [comment]
I've written this: https://laravelactions.com/2.x/register-as-controller.html#routes-with-explicit-methods

And I've just made sure my note at the bottom is correct haha.

Do you mean you'd like to mention alternative ways to handle the show/process forms duality? Like using `ShowX` actions as I mentioned on issue #110?

**Comment by Wulfheart** [comment]
Oh yes. This one is gold.

**Comment by lorisleiva** [comment]
Documentation updated 👌

**Pull request merged**
